version: '3.12'

services:
  postgres:
    image: postgres:16
    container_name: db_postgress
    restart: always
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
      build: .
      container_name: app
      depends_on:
        - postgres
      environment:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
        - DATABASE_URL=${DATABASE_URL}
      env_file:
        - .env
      command: python -u main.py  # -u flag para unbuffered output
      tty: true  # Mantém o terminal aberto
      stdin_open: true 

volumes:
  pgdata:


