version: '3.12'

services:
  postgres:
    image: postgres:16
    container_name: db_postgress
    restart: always
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - postgres
    env_file:
      - .env
    command: conda run --no-capture-output -n gntech python main.py
    tty: true
    stdin_open: true

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: conda run --no-capture-output -n gntech uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    tty: true
    stdin_open: true

volumes:
  pgdata:


